feat: organize blog articles
fireflyhealth/marketing-website pull request #80
Opened 2024-11-07 22:40 UTC by bryanwash

### Description

- adds sorting feature to `blog` schema

Addresses this [maintenance ticket](https://www.notion.so/garden3d/a2ad8d447b914caa95ba0f01214ed512?v=69f7a661391d40eb966fce5affc5720c&p=69ef77b6ceac4e74ad49effad421031d&pm=s) 

### Feedback & Concerns

### QA Instructions

### Applicable screenshots or Loom video
![Screenshot 2024-11-07 at 5 35 14 PM](https://github.com/user-attachments/assets/74029607-962a-44b0-8efb-9143fb5be3ec)
![Screenshot 2024-11-07 at 5 36 04 PM](https://github.com/user-attachments/assets/842410e1-331d-4632-9c5b-76b675d3eddf)
![Screenshot 2024-11-07 at 5 35 28 PM](https://github.com/user-attachments/assets/8ca0a144-aafe-4bbc-9e07-b7c6fe2373ea)
![Screenshot 2024-11-07 at 5 35 52 PM](https://github.com/user-attachments/assets/8e1902c7-3a91-4f7e-bf1c-3b812b03f107)

2024-11-11 15:46 UTC, limsohee1002 requested changes

2024-11-11 15:46 UTC, limsohee1002 commented on www/src/pages/blog/[blogSlug]/index.tsx
> +};
We should sort the articles when we fetch since we are using pagination. It will only sort within fetched articles not all articles.

2024-11-11 15:46 UTC, limsohee1002 commented on www/src/types/sanity.ts
> +export type ArticleSortOrder = 'sortAutomatically' | 'sortManually';
We cannot assume this data will always be here, even if the field is required. Since this is an update to the existing schema, even if the field is required, the already published document will not have this data and will have other data. Also, we are using local CMS, which is even harder to track. We should assume this field can be `null` given our condition.

2024-11-11 15:46 UTC, limsohee1002 commented on www/src/views/Blog/BlogArticlesGrid.tsx
> +  // const sortedArticles = sortArticles(sortOrder, currentPage.articles);
remove this?

2024-11-11 15:51 UTC, limsohee1002 commented on www/src/pages/blog/[blogSlug]/index.tsx
> +};
https://www.sanity.io/docs/query-cheat-sheet#b5aec96cf56c

2024-11-11 15:58 UTC, bryanwash commented on www/src/pages/blog/[blogSlug]/index.tsx
> +};
@limsohee1002 I was thinking about setting it up in this way.  That would mean:

Updating how we are fetching blog articles in `getStaticProps` by passing in a new prop to `getBlogArticles` based on the sort method set in Sanity
- Automatically - use the same query but update it so it sets the order of articles by _updatedAt (desc)
- Manually - create a new query that fetches articles directly from the list of articles added to the blog index document

Does that sound about right to you?

2024-11-12 14:08 UTC, limsohee1002 commented on www/src/pages/blog/[blogSlug]/index.tsx
> +};
Yup, that sounds kind of right. Manually is correct; for "automatic" articles, there are "updated date" and "published date" fields in the article document. If that field has value, we should use that value instead of `_updatedAt` value. Also, isn't the `_updatedAt` value empty if the editor never updates the article? 
<img width="666" alt="image" src="https://github.com/user-attachments/assets/debf8644-9088-496b-90ec-736ca9b91a9e">

I think the ordering logic should look for `upatedDate || _updatedAt || publishedDate || _publishedAt` something like this. 
Also, the "automatic" article fetch logic has pagination, so we need to use `groq` to fetch the articles in order so that it sorts "all" articles. If you fetch articles and sort them on the front end, you will only sort the articles you got on the first page, not all articles.

2024-11-12 14:12 UTC, limsohee1002 commented on www/src/lib/sanity/index.ts
> +  ] | order(_updatedAt desc) | order(publishDate desc) {
🎉 Yup this is what I was thinking, we have `updatedDate` field as well, can we add that field here as well so that if editor fill out that field, we should use that field instead of `_updatedAt`

2024-11-12 14:17 UTC, limsohee1002 commented
When I test it locally, the article is empty, can you check this?
<img width="985" alt="image" src="https://github.com/user-attachments/assets/062f2469-e8fe-4361-bf3c-e03ec5050503">

2024-11-12 15:38 UTC, bryanwash commented
> When I test it locally, the article is empty, can you check this? <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/30321742/385319883-062f2469-e8fe-4361-bf3c-e03ec5050503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjQxNDcsIm5iZiI6MTczMTQyMzg0NywicGF0aCI6Ii8zMDMyMTc0Mi8zODUzMTk4ODMtMDYyZjI0NjktZThmZS00MzYxLWJmM2MtZTAzZWM1MDUwNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1MDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Yzc4NTE5OWU3OGQ2ZGZhOWEwN2I4ZjMxNjgxOTk1NWJkN2Y4MjMzYzFjMjdiOTdlNjA3NGI2YTdjMzU5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Z37oQyJ1EXb_4eY-jBBxrZ-bkOrnvyh5yG1WqYs4Wk">

@limsohee1002 Yes, I was spinning my wheels trying to figure out why this is happening.  Can you take a look at the `getManuallySortedBlogArticles` I created to make sure I'm not completely missing something?

2024-11-13 14:07 UTC, limsohee1002 commented
> > When I test it locally, the article is empty, can you check this? <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/30321742/385319883-062f2469-e8fe-4361-bf3c-e03ec5050503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjQxNDcsIm5iZiI6MTczMTQyMzg0NywicGF0aCI6Ii8zMDMyMTc0Mi8zODUzMTk4ODMtMDYyZjI0NjktZThmZS00MzYxLWJmM2MtZTAzZWM1MDUwNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1MDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Yzc4NTE5OWU3OGQ2ZGZhOWEwN2I4ZjMxNjgxOTk1NWJkN2Y4MjMzYzFjMjdiOTdlNjA3NGI2YTdjMzU5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Z37oQyJ1EXb_4eY-jBBxrZ-bkOrnvyh5yG1WqYs4Wk">
> 
> @limsohee1002 Yes, I was spinning my wheels trying to figure out why this is happening. Can you take a look at the `getManuallySortedBlogArticles` I created to make sure I'm not completely missing something?

I'm not sure I understand correctly. Is this PR incomplete? or was it working before, and you changed something, and it is not working anymore?

2024-11-15 18:14 UTC, limsohee1002 commented
@bryanwash can you check if this works now on your end? 🙏

2024-11-15 18:27 UTC, bryanwash commented
@limsohee1002 Tested on my end.  Looks good!

2024-11-15 19:11 UTC, limsohee1002 submitted a review, later dismissed

2024-11-21 15:47 UTC, limsohee1002 approved these changes

2024-11-21 15:53 UTC, limsohee1002 commented
@shivananda-sahu Hey Shiva, could you please review this and approve it? Since Bryan and I worked on it together, we need another person to approve to merge i think 🙏

2024-11-21 19:43 UTC, limsohee1002 commented
Created other PR to bypass merge here: https://github.com/fireflyhealth/marketing-website/pull/88

2024-11-21 19:43 UTC, closed without merging